# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Atmana Joshi
tagline:          'Biomedical Researcher'
description:      'Biomedical Sciences at Ichan School of Medicine, Mount Sinai, NY'
url:              http://atmanajoshi.github.io

author:
  name:           'Atmana Joshi'
  email:          atmanajoshi@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/atmanajoshi

gems: [jekyll-paginate]
since:                  2024
google_analytics:       UA-63207330-1
emailme:                mailto:atmanajoshi@gmail.com
github:
  repo:                 https://github.com/atmanajoshi
version:                Jul.19.2024
googlescholar_username: XDvADooAAAAJ
linkedin_username:      atmana-joshi
github_username:        atmanajoshi
share_pdf:              no
share_video:            no
# facebook_username: 
# google_plus_username: 
# twitter_username: 
# instagram_username:

collections:
  publications:
    output: true
  contact:
    output: true
  resume:
    output: true
  projects:
    output: true
  home:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
