# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Manal Shah
tagline:          'Start here, make a difference'
description:      'Raised in India, now based in New York, USA. CS Grad @StonyBrook'
url:              http://mbshah3.github.io
baseurl:          /

author:
  name:           'Manal Shah'
  email:          manal.shah@stonybrook.edu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/manal3112

gems: [jekyll-paginate]

# custom vars
since:                  2015
google_analytics:       UA-63207330-1
emailme:                mailto:manal.shah@stonybrook.edu
github:
  repo:                 https://github.com/manal3112
version:                Aug.16.2022
googlescholar_username: XDvADooAAAAJ
linkedin_username:      manalshah31
github_username:        manal3112
share_pdf:              no
share_video:            no
# facebook_username: 
# google_plus_username: 
# twitter_username: 
# instagram_username: 
# cv_chn: yes
